Repository Venox-Network/cobalt, pull requests merged in 2022-05, with the labels that each got.

#50 Added superkick and fixed superban #49
  bot.py
  cogs/ban.py
  cogs/info.py
  cogs/kick.py
  cogs/leaveserver.py
  cogs/music.py
  cogs/mutes.py
  cogs/purge.py
  cogs/reports.py
  cogs/superban.py
  cogs/superkick.py
  cogs/warnings.py
Labels: bug, enhancement, python

#54 Fixed kick, superban, and unsuperban
  cogs/autothread.py
  cogs/info.py
  cogs/kick.py
  cogs/leaveserver.py
  cogs/reports.py
  cogs/superban.py
  cogs/warnings.py
Labels: bug

#57 Made react ephormal, added sticky message
  cogs/autothread.py
  cogs/dynamicslowmode.py
  cogs/nicknamemod.py
  cogs/react.py
  cogs/stickymessage.py
Labels: enhancement, python

#58 OOP Bot rewrite
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/enhancement.yml
  .gitignore
  README.md
  bot.py
  cogs/autothread.py
  cogs/ban.py
  cogs/dynamicslowmode.py
  cogs/info.py
  cogs/kick.py
  cogs/leaveserver.py
  cogs/music.py
  cogs/mutes.py
  cogs/nicknamemod.py
  cogs/purge.py
  cogs/react.py
  cogs/reports.py
  cogs/stickymessage.py
  cogs/superban.py
  cogs/superkick.py
  cogs/warnings.py
  project.json
  requirements.txt
  src/cogs/__init__.py
  src/cogs/auto_thread.py
  src/cogs/fun_commands.py
  src/cogs/info_commands.py
  src/cogs/music_commands.py
  src/cogs/nick_name_commands.py
  src/cogs/report_commands.py
  src/cogs/slowmode_commands.py
  src/cogs/staff_commands.py
  src/cogs/sticky_message.py
  src/cogs/super_commands.py
  src/cogs/time_jobs.py
  src/config.py
  src/discord_bot.py
  src/venox.py
Labels: big, python
